### ISSUE TITLE
17-Card

### ISSUE THREAD

**Issue by tsotneforester** [feraldruid1/JAVASCRIPT#6]
![99](https://user-images.githubusercontent.com/79293287/231339415-09c932ae-afb8-45a6-85d3-d8327036574f.png)
![5](https://user-images.githubusercontent.com/79293287/231339423-8a41270e-0905-4ddf-891f-85fee207d308.png)

**Comment by tsotneforester** [comment]
წრეწირი ცოტა ჩამოწიე, ზუსტად სუასი უნდა იყოს, ოგნავ ზევითაა შენი

**Comment by feraldruid1** [comment]
ჩამოვწიე
